2023-03-09 15:07:24,291 INFO    MainThread:1897045 [wandb_setup.py:_flush():68] Configure stats pid to 1897045
2023-03-09 15:07:24,291 INFO    MainThread:1897045 [wandb_setup.py:_flush():68] Loading settings from /home/aditya_sharma/.config/wandb/settings
2023-03-09 15:07:24,291 INFO    MainThread:1897045 [wandb_setup.py:_flush():68] Loading settings from /home/aditya_sharma/281/pytorch-CycleGAN-and-pix2pix/wandb/settings
2023-03-09 15:07:24,291 INFO    MainThread:1897045 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-09 15:07:24,291 INFO    MainThread:1897045 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'test.py', 'program': '/home/aditya_sharma/281/pytorch-CycleGAN-and-pix2pix/test.py'}
2023-03-09 15:07:24,291 INFO    MainThread:1897045 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-09 15:07:24,292 INFO    MainThread:1897045 [wandb_init.py:_log_setup():492] Logging user logs to /home/aditya_sharma/281/pytorch-CycleGAN-and-pix2pix/wandb/run-20230309_150724-fa2bt4zw/logs/debug.log
2023-03-09 15:07:24,292 INFO    MainThread:1897045 [wandb_init.py:_log_setup():493] Logging internal logs to /home/aditya_sharma/281/pytorch-CycleGAN-and-pix2pix/wandb/run-20230309_150724-fa2bt4zw/logs/debug-internal.log
2023-03-09 15:07:24,292 INFO    MainThread:1897045 [wandb_init.py:init():532] calling init triggers
2023-03-09 15:07:24,292 INFO    MainThread:1897045 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {'dataroot': './datasets/bird/', 'name': 'bird_pix2pix', 'gpu_ids': [0], 'checkpoints_dir': './checkpoints', 'model': 'pix2pix', 'input_nc': 3, 'output_nc': 3, 'ngf': 64, 'ndf': 64, 'netD': 'basic', 'netG': 'unet_256', 'n_layers_D': 3, 'norm': 'batch', 'init_type': 'normal', 'init_gain': 0.02, 'no_dropout': False, 'dataset_mode': 'aligned', 'direction': 'BtoA', 'serial_batches': True, 'num_threads': 0, 'batch_size': 1, 'load_size': 256, 'crop_size': 256, 'max_dataset_size': inf, 'preprocess': 'resize_and_crop', 'no_flip': True, 'display_winsize': 256, 'epoch': 'latest', 'load_iter': 0, 'verbose': False, 'suffix': '', 'use_wandb': True, 'wandb_project_name': 'CycleGAN-and-pix2pix', 'results_dir': './results/', 'aspect_ratio': 1.0, 'phase': 'test', 'eval': False, 'num_test': 50, 'isTrain': False, 'display_id': -1}
2023-03-09 15:07:24,293 INFO    MainThread:1897045 [wandb_init.py:init():588] starting backend
2023-03-09 15:07:24,293 INFO    MainThread:1897045 [wandb_init.py:init():592] setting up manager
2023-03-09 15:07:24,296 INFO    MainThread:1897045 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-09 15:07:24,299 INFO    MainThread:1897045 [wandb_init.py:init():599] backend started and connected
2023-03-09 15:07:24,303 INFO    MainThread:1897045 [wandb_init.py:init():687] updated telemetry
2023-03-09 15:07:24,347 INFO    MainThread:1897045 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-09 15:07:24,656 INFO    MainThread:1897045 [wandb_run.py:_on_init():2134] communicating current version
2023-03-09 15:07:24,714 INFO    MainThread:1897045 [wandb_run.py:_on_init():2143] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-09 15:07:24,714 INFO    MainThread:1897045 [wandb_init.py:init():775] starting run threads in backend
2023-03-09 15:07:25,211 INFO    MainThread:1897045 [wandb_run.py:_console_start():2114] atexit reg
2023-03-09 15:07:25,211 INFO    MainThread:1897045 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-09 15:07:25,212 INFO    MainThread:1897045 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-09 15:07:25,212 INFO    MainThread:1897045 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-09 15:07:25,213 INFO    MainThread:1897045 [wandb_init.py:init():817] run started, returning control to user process
2023-03-09 15:07:35,505 WARNING MsgRouterThr:1897045 [router.py:message_loop():77] message_loop has been closed
